# -*- coding: utf-8 -*-
"""Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipb8Fu2bp5GGmrDGEttvxZv2yHcpmWsL
"""

import os
print(os.getcwd())
print(os.listdir())

# Phase 1: Data Preparation & Ingestion
# -------------------------------------
# Colab code for profiling & cleaning datasets

import pandas as pd
import re
import os
from sklearn.model_selection import train_test_split

# File paths (update if stored differently in Colab)
incident_src = "/content/src_incident_records.csv"
tech_src = "/content/src_tech_records.csv"
incident_meta = "/content/metadata_incident_records.csv"
tech_meta = "/content/metadata_tech_records.csv"

# Load datasets
df_incident = pd.read_csv(incident_src)
df_tech = pd.read_csv(tech_src)
df_incident_meta = pd.read_csv(incident_meta)
df_tech_meta = pd.read_csv(tech_meta)

print("✅ Data Loaded")

# ---------------------------
# 1. Data Profiling
# ---------------------------
def profile_data(df, name):
    print(f"\n=== Profiling {name} ===")
    print(df.info())
    print("\nMissing values:\n", df.isnull().sum())
    print("\nDuplicate rows:", df.duplicated().sum())
    print("\nSample rows:\n", df.head(2))

profile_data(df_incident, "Source Incidents")
profile_data(df_tech, "Source Technical Records")

# ---------------------------
# 2. Data Cleaning Functions
# ---------------------------
def clean_text(text):
    if pd.isna(text):
        return ""
    text = str(text)
    text = text.encode("utf-8", "ignore").decode()  # standardize encoding
    text = re.sub(r"\s+", " ", text).strip()       # normalize whitespace
    return text

# Apply cleaning
df_incident["ProblemDescription"] = df_incident["ProblemDescription"].apply(clean_text)
df_tech["step_description"] = df_tech["step_description"].apply(clean_text)

# ---------------------------
# 3. Chunking Long Descriptions (>1 KB)
# ---------------------------
def chunk_text(text, max_len=1000):
    if len(text.encode("utf-8")) <= max_len:
        return [text]
    chunks, current = [], ""
    for word in text.split():
        if len((current + " " + word).encode("utf-8")) > max_len:
            chunks.append(current.strip())
            current = word
        else:
            current += " " + word
    if current:
        chunks.append(current.strip())
    return chunks

# Expand incident records
incident_expanded = []
for _, row in df_incident.iterrows():
    chunks = chunk_text(row["ProblemDescription"])
    for i, chunk in enumerate(chunks):
        incident_expanded.append({
            "TicketID": row["TicketID"],
            "ProductID": row["ProductID"],
            "ChunkID": f"{row['TicketID']}_chunk{i+1}",
            "ProblemDescription": chunk
        })

df_incident_clean = pd.DataFrame(incident_expanded)

# Expand technical records
tech_expanded = []
for _, row in df_tech.iterrows():
    chunks = chunk_text(row["step_description"])
    for i, chunk in enumerate(chunks):
        tech_expanded.append({
            "DocID": row["DocID"],
            "ProductID": row["ProductID"],
            "ChunkID": f"{row['DocID']}_chunk{i+1}",
            "step_description": chunk
        })

df_tech_clean = pd.DataFrame(tech_expanded)

# ---------------------------
# 4. Remove Customer Identifiers (from metadata)
# ---------------------------
if "CustomerID" in df_incident_meta.columns:
    df_incident_meta = df_incident_meta.drop(columns=["CustomerID"])
    print("✅ CustomerID column removed from metadata_incident_records")

# ---------------------------
# 5. Save Cleaned Data
# ---------------------------
os.makedirs("cleaned_data", exist_ok=True)

df_incident_clean.to_csv("cleaned_data/clean_incident_records.csv", index=False)
df_tech_clean.to_csv("cleaned_data/clean_tech_records.csv", index=False)
df_incident_meta.to_csv("cleaned_data/clean_metadata_incident.csv", index=False)
df_tech_meta.to_csv("cleaned_data/clean_metadata_tech.csv", index=False)

print("\n✅ Cleaning Complete. Files saved in 'cleaned_data/' folder.")