# -*- coding: utf-8 -*-
"""Agent to Agent Communication.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipb8Fu2bp5GGmrDGEttvxZv2yHcpmWsL
"""

# ========================================
# Phase 5 — Agent-to-Agent Communication
# ========================================

import time, json

# Broker Orchestrator
def troubleshooting_pipeline(ticket_text, threshold=0.75):
    """Full pipeline: Agent 1 → Broker → Agent 2 if needed"""
    start_time = time.time()

    # Step 1: Call Agent 1
    try:
        agent1_result = retriever_agent(ticket_text, top_k=5, weight_threshold=0.6)
    except Exception as e:
        print(f"❌ Agent 1 error: {e}. Routing directly to Agent 2.")
        agent1_result = {"confidence": 0.0, "used_fallback": True, "error": str(e)}

    # Step 2: Broker Decision
    if agent1_result.get("confidence", 0) >= threshold:
        # Agent 1 accepted
        final_output = response_formatter(agent1_result)
        decision_log = {
            "decision": "accepted_agent1",
            "reason": f"Confidence {agent1_result['confidence']:.2f} ≥ {threshold}"
        }
    else:
        # Fallback to Agent 2
        agent2_result = reasoner_agent(ticket_text, max_retries=2, top_k=3)
        final_output = agent2_result
        decision_log = {
            "decision": "fallback_agent2",
            "reason": f"Confidence {agent1_result.get('confidence', 0):.2f} < {threshold}"
        }

    # Step 3: Add Metadata
    final_output["processing_time_ms"] = round((time.time() - start_time) * 1000, 2)

    # Step 4: Log routing decision
    print("\n📝 Routing Decision Log:", json.dumps(decision_log, indent=2))

    return final_output


# ----------------------------------------
# 🔍 Test End-to-End Workflow
# ----------------------------------------
test_query = "Experiencing latency spikes on router X during peak hours"
pipeline_result = troubleshooting_pipeline(test_query, threshold=0.75)

print("\n🎯 Final Structured Output:")
print(json.dumps(pipeline_result, indent=2))