# -*- coding: utf-8 -*-
"""Agent 2(Fall Back Agent).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipb8Fu2bp5GGmrDGEttvxZv2yHcpmWsL

Phase 4: Agent 2 - Fallback Technical Reasoning (LangGraph)
"""

# ========================================
# Phase 4 — Agent 2: ReasonerAgent (LangGraph style)
# ========================================

import json, time, random
import pandas as pd
from vertexai.generative_models import GenerativeModel

# Load enriched technical metadata
df_tech_meta = pd.read_csv("cleaned_data/clean_metadata_tech.csv")

# Gemini model for reasoning
gemini_model = GenerativeModel("gemini-2.0-flash")

def reasoner_agent(ticket_text, max_retries=2, top_k=5):
    """Fallback Agent 2 using Chroma + Gemini for reasoning"""
    # Step 1: Embed ticket text
    query_emb = embedding_model.get_embeddings([ticket_text])[0].values

    # Step 2: Query Chroma (technical docs)
    results = tech_collection.query(
        query_embeddings=[query_emb],
        n_results=top_k,
        include=["documents", "metadatas", "distances"]
    )

    docs = results["documents"][0]
    metas = results["metadatas"][0]

    # Step 3: Get solution steps from metadata
    context_snippets = []
    for meta, doc in zip(metas, docs):
        doc_id = meta["doc_id"]
        sol_row = df_tech_meta[df_tech_meta["DocID"] == doc_id]
        solution_steps = sol_row["SolutionSteps"].iloc[0] if not sol_row.empty else "No documented steps."

        context_snippets.append(f"- Problem Context: {doc}\n- Solution Steps: {solution_steps}")

    # Step 4: Build few-shot prompt
    prompt = f"""
You are a network troubleshooting assistant.

Ticket Issue:
{ticket_text}

Reference Technical Documentation (Top {len(context_snippets)} Matches):
{chr(10).join(context_snippets)}

Instruction:
Return a concise resolution with up to 5 technical steps.
Format as a numbered list.
"""

    # Step 5: Retry logic with exponential backoff
    for attempt in range(max_retries):
        try:
            response = gemini_model.generate_content(prompt)
            text_output = response.candidates[0].content.parts[0].text

            # Basic validation: must contain at least one numbered step
            if "1." not in text_output:
                raise ValueError("Malformed output: missing steps")

            return {
                "query": ticket_text,
                "agent_source": "agent_2",
                "used_fallback": True,
                "technical_resolution": text_output.strip(),
                "confidence": None,
                "status": "SUCCESS"
            }
        except Exception as e:
            wait = 2 ** attempt + random.random()
            print(f"⚠️ Agent 2 error: {e}. Retrying in {wait:.1f}s...")
            time.sleep(wait)

    # Step 6: Graceful degradation
    return {
        "query": ticket_text,
        "agent_source": "agent_2",
        "used_fallback": True,
        "technical_resolution": None,
        "status": "AGENT2_FAILED"
    }

# ----------------------------------------
# 🔍 Test ReasonerAgent
# ----------------------------------------
low_conf_query = "Router X keeps dropping packets after config change"
response_agent2 = reasoner_agent(low_conf_query, max_retries=2, top_k=3)

print("\n🎯 Agent 2 Final Output:")
print(json.dumps(response_agent2, indent=2))