# -*- coding: utf-8 -*-
"""Retreiver Agent(Agent 1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipb8Fu2bp5GGmrDGEttvxZv2yHcpmWsL

Phase 3.1 — RetrieverAgent (AutoGen / Chroma)
"""

# ========================================
# Phase 3 — Agent 1: RetrieverAgent
# ========================================

import pandas as pd
import numpy as np

# Load enriched incident metadata (contains solution details)
df_incident_meta = pd.read_csv("cleaned_data/clean_metadata_incident.csv")

def retriever_agent(query_text, top_k=5, weight_threshold=0.6):
    """RetrieverAgent using Chroma for similarity search"""
    # Step 1: Embed query
    query_emb = embedding_model.get_embeddings([query_text])[0].values

    # Step 2: Query Chroma
    results = incident_collection.query(
        query_embeddings=[query_emb],
        n_results=top_k,
        include=["documents", "metadatas", "distances"]
    )

    docs = results["documents"][0]
    metas = results["metadatas"][0]
    dists = results["distances"][0]

    # Step 3: Convert distances → cosine similarity
    sims = [1 - d for d in dists]
    norm_sims = np.array(sims) / np.sum(sims)  # normalize

    # Step 4: Aggregate until cumulative weight > threshold
    cumulative, selected_solutions = 0.0, []
    for doc, meta, sim, w in zip(docs, metas, sims, norm_sims):
        # Lookup solution details from metadata file
        ticket_id = meta["ticket_id"]
        sol_row = df_incident_meta[df_incident_meta["TicketID"] == ticket_id]
        solution = sol_row["SolutionDetails"].iloc[0] if not sol_row.empty else "No solution found"

        selected_solutions.append({
            "ticket_id": ticket_id,
            "product_id": meta["product_id"],
            "retrieved_problem": doc,
            "solution": solution,
            "similarity": round(sim, 3),
            "weight": round(float(w), 3)
        })
        cumulative += w
        if cumulative >= weight_threshold:
            break

    # Step 5: Compute confidence (average of sims)
    confidence = float(np.mean(sims[:len(selected_solutions)]))

    # Step 6: Output payload
    response = {
        "query": query_text,
        "proposed_solutions": [s["solution"] for s in selected_solutions],
        "confidence": round(confidence, 3),
        "used_fallback": False,
        "agent_source": "agent_1",
        "retrieved_records": selected_solutions
    }
    return response

# -----------------------------
# 🔍 Test RetrieverAgent
# -----------------------------
test_query = "Experiencing latency spikes on router X during peak hours"
response = retriever_agent(test_query, top_k=5, weight_threshold=0.6)

import json
print(json.dumps(response, indent=2))

