# -*- coding: utf-8 -*-
"""Threshold decision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipb8Fu2bp5GGmrDGEttvxZv2yHcpmWsL

threshold decision
"""

# ========================================
# Phase 3.2 — Threshold Decision
# ========================================

def threshold_decision(agent1_response, threshold=0.75):
    """Decide whether to accept Agent 1 or trigger fallback Agent 2"""
    confidence = agent1_response["confidence"]

    log_entry = {
        "query": agent1_response["query"],
        "confidence": confidence,
        "decision": None,
        "reason": None
    }

    if confidence >= threshold:
        # Forward to ResponseFormatter
        log_entry["decision"] = "accepted_agent1"
        log_entry["reason"] = f"Confidence {confidence:.2f} ≥ {threshold}"
        agent1_response["used_fallback"] = False
        final_output = response_formatter(agent1_response)
    else:
        # Trigger fallback Agent 2
        log_entry["decision"] = "fallback_agent2"
        log_entry["reason"] = f"Confidence {confidence:.2f} < {threshold}"
        agent1_response["used_fallback"] = True
        final_output = {
            "status": "ROUTE_TO_AGENT2",
            "query": agent1_response["query"],
            "confidence": confidence,
            "reason": log_entry["reason"]
        }

    # Log decision
    print("\n📝 Threshold Decision Log:", json.dumps(log_entry, indent=2))
    return final_output


# ----------------------------------------
# Simple ResponseFormatter
# ----------------------------------------
def response_formatter(agent1_response):
    """Format final output if Agent 1 is accepted"""
    return {
        "ticket_id": agent1_response["retrieved_records"][0]["ticket_id"],
        "proposed_solution": agent1_response["proposed_solutions"],
        "confidence": agent1_response["confidence"],
        "used_fallback": agent1_response["used_fallback"],
        "agent_source": agent1_response["agent_source"]
    }

# ----------------------------------------
# 🔍 Test with a sample query
# ----------------------------------------
test_query = "Router experiencing high latency during peak usage"
agent1_result = retriever_agent(test_query, top_k=5, weight_threshold=0.6)

final_decision = threshold_decision(agent1_result, threshold=0.75)

print("\n🎯 Final Output:")
print(json.dumps(final_decision, indent=2))