# -*- coding: utf-8 -*-
"""FAST_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipb8Fu2bp5GGmrDGEttvxZv2yHcpmWsL
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile fastapi_app.py
# from fastapi import FastAPI, Request
# from pydantic import BaseModel
# import json
# import numpy as np
# import time
# from sentence_transformers import SentenceTransformer
# import google.generativeai as genai
# import logging
# from google.cloud import monitoring_v3
# import threading
# 
# # -------- Setup --------
# app = FastAPI(title="Incident Troubleshooter API (Gemini RAG)")
# logger = logging.getLogger("uvicorn.error")
# 
# # -------------------- GCP Monitoring Setup --------------------
# PROJECT_ID = "ishikagcp027"
# PROJECT_NAME = f"projects/{PROJECT_ID}"
# client = monitoring_v3.MetricServiceClient()
# 
# # Track last push times for GAUGE metrics
# _last_push_times = {}
# 
# def write_gauge_metric(metric_type: str, value: float, labels: dict = None, min_interval: float = 10.0):
#     """
#     Push a GAUGE metric to Cloud Monitoring, rate-limited by min_interval (seconds).
#     """
#     def _push():
#         try:
#             series = monitoring_v3.TimeSeries()
#             series.metric.type = f"custom.googleapis.com/{metric_type}"
#             if labels:
#                 series.metric.labels.update(labels)
# 
#             series.resource.type = "global"
#             series.resource.labels["project_id"] = PROJECT_ID
# 
#             # Value
#             point = monitoring_v3.Point()
#             point.value.double_value = float(value)
# 
#             # Time interval
#             now = time.time()
#             interval = monitoring_v3.TimeInterval(
#                 end_time={"seconds": int(now), "nanos": int((now - int(now)) * 1e9)}
#             )
#             point.interval = interval
#             series.points.append(point)
# 
#             client.create_time_series(name=PROJECT_NAME, time_series=[series])
#             logger.info(f"✅ GAUGE metric pushed: {metric_type}={value}")
#         except Exception as e:
#             logger.exception(f"❌ Failed to push GAUGE metric {metric_type}: {e}")
# 
#     # Rate-limit by min_interval
#     now = time.time()
#     last = _last_push_times.get(metric_type, 0)
#     if now - last >= min_interval:
#         _last_push_times[metric_type] = now
#         threading.Thread(target=_push, daemon=True).start()
# 
# 
# def increment_counter(metric_type: str, value: int = 1, labels: dict = None):
#     """
#     Push a CUMULATIVE counter metric to Cloud Monitoring.
#     """
#     def _push():
#         try:
#             series = monitoring_v3.TimeSeries()
#             series.metric.type = f"custom.googleapis.com/{metric_type}"
#             if labels:
#                 series.metric.labels.update(labels)
# 
#             series.resource.type = "global"
#             series.resource.labels["project_id"] = PROJECT_ID
# 
#             # Cumulative counter
#             point = monitoring_v3.Point()
#             point.value.int64_value = value
#             now = time.time()
#             interval = monitoring_v3.TimeInterval(
#                 start_time={"seconds": int(now), "nanos": int((now - int(now)) * 1e9)},
#                 end_time={"seconds": int(now), "nanos": int((now - int(now)) * 1e9)},
#             )
#             point.interval = interval
#             series.points.append(point)
# 
#             client.create_time_series(name=PROJECT_NAME, time_series=[series])
#             logger.info(f"✅ Counter metric incremented: {metric_type} +{value}")
#         except Exception as e:
#             logger.exception(f"❌ Failed to push counter metric {metric_type}: {e}")
# 
#     threading.Thread(target=_push, daemon=True).start()
# 
# 
# # -------------------- Gemini / Embeddings --------------------
# genai.configure(api_key="AIzaSyCbcI092g19B-e7XeFL9soRE2L8E6BPg1o")
# gemini_model = genai.GenerativeModel("gemini-1.5-flash")
# 
# with open("/content/embeddings/incident_embeddings.jsonl", "r") as f:
#     incident_data = [json.loads(line) for line in f]
# 
# with open("/content/embeddings/tech_embeddings.jsonl", "r") as f:
#     tech_data = [json.loads(line) for line in f]
# 
# incident_embeddings = np.array([rec["embedding"] for rec in incident_data])
# tech_embeddings = np.array([rec["embedding"] for rec in tech_data])
# 
# incident_map = {rec["ticket_id"]: rec for rec in incident_data}
# tech_map = {rec["doc_id"]: rec for rec in tech_data}
# 
# embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
# 
# 
# # -------------------- Pydantic Models --------------------
# class IncidentRequest(BaseModel):
#     ticket_id: str | None = None
#     query: str | None = None
# 
# class SolutionResponse(BaseModel):
#     input_used: str
#     proposed_solution: list[str]
#     confidence: float
#     used_fallback: bool
#     agent_source: str
#     processing_time_ms: int
# 
# 
# # -------------------- Utility Functions --------------------
# def cosine_similarity(a, b):
#     a = a / np.linalg.norm(a)
#     b = b / np.linalg.norm(b)
#     return np.dot(a, b)
# 
# 
# # -------------------- Middleware --------------------
# @app.middleware("http")
# async def track_response_time(request: Request, call_next):
#     start = time.time()
#     response = await call_next(request)
#     duration = time.time() - start
# 
#     # GAUGE metric: push at most every 10 seconds
#     write_gauge_metric("fastapi/response_time", duration, min_interval=10.0)
#     return response
# 
# 
# # -------------------- API Endpoint --------------------
# @app.post("/solve", response_model=SolutionResponse)
# def solve_ticket(req: IncidentRequest):
#     start = time.time()
# 
#     try:
#         # -------- Ticket ID Lookup --------
#         if req.ticket_id:
#             ticket_id = req.ticket_id
#             if ticket_id not in incident_map:
#                 return SolutionResponse(
#                     input_used=f"ticket_id={ticket_id}",
#                     proposed_solution=["No solution found for this incident."],
#                     confidence=0.0,
#                     used_fallback=True,
#                     agent_source="agent_2",
#                     processing_time_ms=int((time.time() - start) * 1000),
#                 )
# 
#             incident_emb = np.array(incident_map[ticket_id]["embedding"])
#             sims = [cosine_similarity(incident_emb, np.array(t["embedding"])) for t in tech_data]
#             best_idx = int(np.argmax(sims))
#             best_match = tech_data[best_idx]
# 
#             processing_time = int((time.time() - start) * 1000)
#             increment_counter("tickets_resolved", 1)
#             increment_counter("agent_usage", 1, labels={"agent": "agent_1"})
# 
#             return SolutionResponse(
#                 input_used=f"ticket_id={ticket_id}",
#                 proposed_solution=[best_match.get("text", "No text available")],
#                 confidence=float(sims[best_idx]),
#                 used_fallback=False,
#                 agent_source="agent_1",
#                 processing_time_ms=processing_time,
#             )
# 
#         # -------- Free-text Query --------
#         elif req.query:
#             query = req.query
#             query_emb = embedding_model.encode(query)
# 
#             sims = [cosine_similarity(query_emb, np.array(t["embedding"])) for t in tech_data]
#             top_k = 3
#             top_indices = np.argsort(sims)[::-1][:top_k]
#             retrieved_docs = [tech_data[i]["text"] for i in top_indices]
# 
#             context = "\n\n".join(retrieved_docs)
#             llm_prompt = f"""You are a telecom troubleshooting assistant.
# Use the following past solutions to suggest the best fix.
# 
# Context from past tickets/docs:
# {context}
# 
# User query: {query}
# 
# Give a clear, concise solution suggestion based on above context."""
# 
#             try:
#                 llm_response = gemini_model.generate_content(llm_prompt)
#                 answer = getattr(llm_response, "text", "⚠️ No text in Gemini response")
#             except Exception as e:
#                 logger.exception("Gemini API call failed")
#                 return SolutionResponse(
#                     input_used=f"query='{query}'",
#                     proposed_solution=[f"⚠️ Gemini API error: {str(e)}"],
#                     confidence=0.0,
#                     used_fallback=True,
#                     agent_source="agent_llm",
#                     processing_time_ms=int((time.time() - start) * 1000),
#                 )
# 
#             processing_time = int((time.time() - start) * 1000)
#             increment_counter("tickets_resolved", 1)
#             increment_counter("agent_usage", 1, labels={"agent": "agent_llm"})
# 
#             return SolutionResponse(
#                 input_used=f"query='{query}'",
#                 proposed_solution=[answer],
#                 confidence=float(max(sims)),
#                 used_fallback=False,
#                 agent_source="agent_llm",
#                 processing_time_ms=processing_time,
#             )
# 
#         # -------- No Input --------
#         else:
#             return SolutionResponse(
#                 input_used="None",
#                 proposed_solution=["You must provide either ticket_id or query."],
#                 confidence=0.0,
#                 used_fallback=True,
#                 agent_source="system",
#                 processing_time_ms=int((time.time() - start) * 1000),
#             )
# 
#     except Exception as e:
#         logger.exception("Unexpected error in /solve")
#         raise
#