# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipb8Fu2bp5GGmrDGEttvxZv2yHcpmWsL
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# import streamlit as st
# import requests
# import pandas as pd
# import json
# from datetime import datetime
# from google import genai  # Gemini client
# 
# # =========================
# # CONFIG
# # =========================
# FASTAPI_URL = "http://127.0.0.1:8000"
# GEMINI_API_KEY = "AIzaSyCbcI092g19B-e7XeFL9soRE2L8E6BPg1o"  # 🔑 Hardcoded Gemini key
# 
# client = genai.Client(api_key=GEMINI_API_KEY)
# 
# st.set_page_config(page_title="Incident Troubleshooter", page_icon="🛠️", layout="wide")
# st.markdown("<h2 style='text-align: center;'>🛠️ Incident Troubleshooter Chatbot</h2>", unsafe_allow_html=True)
# 
# # =========================
# # SESSION STATE INIT
# # =========================
# if "chat_history" not in st.session_state:
#     st.session_state.chat_history = []  # (sender, message)
# if "history" not in st.session_state:
#     st.session_state.history = []  # structured log
# 
# # =========================
# # CHAT DISPLAY
# # =========================
# chat_container = st.container()
# with chat_container:
#     for sender, message in st.session_state.chat_history:
#         if sender == "user":
#             st.markdown(
#                 f"<div style='text-align: right; background-color: #DCF8C6; "
#                 f"padding:8px; border-radius:10px; margin:5px; max-width:80%; margin-left:auto;'>"
#                 f"<b>You:</b> {message}</div>",
#                 unsafe_allow_html=True,
#             )
#         else:
#             st.markdown(
#                 f"<div style='text-align: left; background-color: #F1F0F0; "
#                 f"padding:8px; border-radius:10px; margin:5px; max-width:80%;'>"
#                 f"<b>Bot:</b> {message}</div>",
#                 unsafe_allow_html=True,
#             )
# 
# # =========================
# # GEMINI FUNCTION
# # =========================
# def call_gemini(query: str) -> str:
#     """Call Gemini for general troubleshooting queries"""
#     try:
#         response = client.models.generate_content(
#             model="gemini-1.5-flash",
#             contents=f"You are a telecom incident troubleshooter. Suggest solutions for:\n{query}"
#         )
#         return response.text.strip()
#     except Exception as e:
#         return f"❌ Gemini API error: {e}"
# 
# # =========================
# # USER INPUT
# # =========================
# mode = st.radio("Select Input Mode:", ["Ticket ID", "Free-text Query"], horizontal=True)
# user_input = st.chat_input("Type your troubleshooting query or incident ID here...")
# 
# if user_input:
#     st.session_state.chat_history.append(("user", user_input))
# 
#     if mode == "Ticket ID":
#         # -------- FASTAPI MODE --------
#         try:
#             with st.spinner("🔍 Fetching solution from knowledge base..."):
#                 resp = requests.post(f"{FASTAPI_URL}/solve", json={"ticket_id": user_input})
# 
#             if resp.status_code == 200:
#                 data = resp.json()
#                 solutions = "\n".join([f"- {s}" for s in data.get("proposed_solution", [])])
#                 bot_message = (
#                     f"**Input Used:** {data['input_used']}\n\n"
#                     f"**Solution(s):**\n{solutions if solutions else 'No solution available.'}\n\n"
#                     f"**Confidence:** {round(data['confidence'], 3)}\n"
#                     f"**Processing Time:** {data['processing_time_ms']} ms\n"
#                     f"**Agent Source:** {data['agent_source']}\n"
#                 )
#                 if data.get("used_fallback"):
#                     bot_message += "\n⚠️ *Fallback solution used. May not be fully accurate.*"
# 
#                 st.session_state.chat_history.append(("bot", bot_message))
# 
#                 st.session_state.history.append({
#                     "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
#                     "input_mode": "Ticket ID",
#                     "input_value": user_input,
#                     "solution": "; ".join(data["proposed_solution"]),
#                     "confidence": round(data["confidence"], 3),
#                     "agent_source": data["agent_source"],
#                     "processing_time_ms": data["processing_time_ms"],
#                 })
#             else:
#                 st.session_state.chat_history.append(("bot", f"❌ API Error: {resp.status_code}"))
# 
#         except requests.exceptions.RequestException as e:
#             st.session_state.chat_history.append(("bot", f"❌ Request failed: {e}"))
# 
#     else:
#         # -------- GEMINI MODE --------
#         with st.spinner("🤖 Looking through solutions..."):
#             answer = call_gemini(user_input)
# 
#         st.session_state.chat_history.append(("bot", answer))
#         st.session_state.history.append({
#             "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
#             "input_mode": "Free-text Query",
#             "input_value": user_input,
#             "solution": answer,
#             "confidence": "LLM",
#             "agent_source": "Gemini",
#             "processing_time_ms": "N/A",
#         })
# 
#     st.rerun()
# 
# # =========================
# # HISTORY + DOWNLOAD
# # =========================
# st.subheader("📜 Query History")
# 
# if st.session_state["history"]:
#     df = pd.DataFrame(st.session_state["history"])
#     st.dataframe(df)
# 
#     csv = df.to_csv(index=False).encode("utf-8")
#     st.download_button("📥 Download History as CSV", data=csv, file_name="troubleshooter_history.csv", mime="text/csv")
# 
#     json_data = json.dumps(st.session_state["history"], indent=2)
#     st.download_button("📥 Download History as JSON", data=json_data, file_name="troubleshooter_history.json", mime="application/json")
# 
#     if st.button("🧹 Clear Chat & History"):
#         st.session_state.chat_history = []
#         st.session_state.history = []
#         st.rerun()
# else:
#     st.info("No queries yet. Start chatting to see history here.")
#