# -*- coding: utf-8 -*-
"""Embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipb8Fu2bp5GGmrDGEttvxZv2yHcpmWsL
"""

import os
import json
import pandas as pd
from google.cloud import storage
import vertexai
from vertexai.preview.language_models import TextEmbeddingModel

# -------------------------
# Config
# -------------------------
PROJECT_ID = "ishikagcp027"     # 🔹 replace with your project ID
LOCATION = "us-central1"               # 🔹 embeddings supported: us-central1, europe-west4, asia-southeast1
BUCKET_NAME = "technet-data"           # 🔹 replace with your bucket name

vertexai.init(project=PROJECT_ID, location=LOCATION)

# -------------------------
# Load cleaned datasets
# -------------------------
df_incident = pd.read_csv("cleaned_data/clean_incident_records.csv")
df_tech = pd.read_csv("cleaned_data/clean_tech_records.csv")

print("✅ Datasets loaded")

# -------------------------
# Initialize embedding model
# -------------------------
embedding_model = TextEmbeddingModel.from_pretrained("text-embedding-004")

def generate_embeddings(texts, batch_size=32):
    """Generate embeddings in batches to avoid memory issues"""
    all_embeddings = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        embeddings = embedding_model.get_embeddings(batch)
        all_embeddings.extend([e.values for e in embeddings])
    return all_embeddings

# -------------------------
# Incident Record Embeddings
# -------------------------
incident_texts = df_incident["ProblemDescription"].tolist()
incident_embeddings = generate_embeddings(incident_texts)

incident_records = []
for i, row in df_incident.iterrows():
    rec = {
        "ticket_id": row["TicketID"],
        "product_id": row["ProductID"],
        "chunk_id": row["ChunkID"],
        "text": row["ProblemDescription"],
        "embedding": incident_embeddings[i]
    }
    incident_records.append(rec)

# -------------------------
# Technical Record Embeddings
# -------------------------
tech_texts = df_tech["step_description"].tolist()
tech_embeddings = generate_embeddings(tech_texts)

tech_records = []
for i, row in df_tech.iterrows():
    rec = {
        "doc_id": row["DocID"],
        "product_id": row["ProductID"],
        "chunk_id": row["ChunkID"],
        "text": row["step_description"],
        "embedding": tech_embeddings[i]
    }
    tech_records.append(rec)

# -------------------------
# Save to JSONL
# -------------------------
os.makedirs("embeddings", exist_ok=True)

incident_path = "embeddings/incident_embeddings.jsonl"
tech_path = "embeddings/tech_embeddings.jsonl"

with open(incident_path, "w") as f:
    for rec in incident_records:
        f.write(json.dumps(rec) + "\n")

with open(tech_path, "w") as f:
    for rec in tech_records:
        f.write(json.dumps(rec) + "\n")

print("✅ Embeddings saved locally as JSONL")

# -------------------------
# Upload to GCS
# -------------------------
storage_client = storage.Client(project=PROJECT_ID)
bucket = storage_client.bucket(BUCKET_NAME)

upload_map = {
    incident_path: "embeddings/incidents/incident_embeddings.jsonl",
    tech_path: "embeddings/technical/tech_embeddings.jsonl"
}

for local_file, gcs_file in upload_map.items():
    blob = bucket.blob(gcs_file)
    blob.upload_from_filename(local_file)
    print(f"⬆️ Uploaded {local_file} → gs://{BUCKET_NAME}/{gcs_file}")

print("🎯 Phase 2.1 Embedding Pipeline complete")