# -*- coding: utf-8 -*-
"""Mlflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipb8Fu2bp5GGmrDGEttvxZv2yHcpmWsL
"""

# ===============================
# MLflow Tracking for Troubleshooter Project
# ===============================


import mlflow
import json
from pyngrok import ngrok
import time # Import time for timestamp logging

# -------------------------------
# 1. Setup MLflow experiment
# -------------------------------
mlflow.set_tracking_uri("file:///content/mlruns")
mlflow.set_experiment("network_troubleshooter")

# -------------------------------
# 2. Example: Embedding Pipeline Logging
# -------------------------------
# Assuming incident_records, tech_records, incident_collection are available from previous cells
# You might need to re-run previous cells if they are not in the current session state

with mlflow.start_run(run_name="embedding_pipeline"):
    # Assuming PROJECT_ID and BUCKET_NAME are defined in previous cells
    # If not, you might need to retrieve them or define them here
    try:
        mlflow.log_param("project_id", PROJECT_ID)
        mlflow.log_param("bucket_name", BUCKET_NAME)
    except NameError:
        print("Warning: PROJECT_ID or BUCKET_NAME not defined. Skipping logging them as params.")
        pass # Continue if PROJECT_ID or BUCKET_NAME are not defined

    mlflow.log_param("embedding_model", "text-embedding-004")

    # Check if incident_records and tech_records are defined before logging metrics/artifacts
    if 'incident_records' in globals() and incident_records:
        mlflow.log_metric("incident_records_count", len(incident_records))
        # Log embedding dimension if records exist
        if incident_records[0] and "embedding" in incident_records[0]:
             mlflow.log_param("embedding_dim", len(incident_records[0]["embedding"]))
    else:
        print("Warning: 'incident_records' not defined or empty. Skipping logging related metrics/params.")

    if 'tech_records' in globals() and tech_records:
        mlflow.log_metric("tech_records_count", len(tech_records))
    else:
         print("Warning: 'tech_records' not defined or empty. Skipping logging related metrics.")


    # Check if embedding directory and files exist before logging artifacts
    if os.path.exists("embeddings/incident_embeddings.jsonl"):
        mlflow.log_artifact("embeddings/incident_embeddings.jsonl")
    else:
        print("Warning: 'embeddings/incident_embeddings.jsonl' not found. Skipping logging artifact.")

    if os.path.exists("embeddings/tech_embeddings.jsonl"):
        mlflow.log_artifact("embeddings/tech_embeddings.jsonl")
    else:
        print("Warning: 'embeddings/tech_embeddings.jsonl' not found. Skipping logging artifact.")


# -------------------------------
# 3. Example: Benchmark Query Logging
# -------------------------------
# Assuming benchmark_query and incident_collection are available
if 'benchmark_query' in globals() and 'incident_collection' in globals():
    query = "Latency spikes on router X"
    # Ensure benchmark_query returns a numeric latency value
    latency = benchmark_query(incident_collection, query, top_k=5, threshold=0.6)

    with mlflow.start_run(run_name="benchmark_query"):
        mlflow.log_param("query", query)
        mlflow.log_metric("query_latency_ms", latency)
else:
    print("Warning: 'benchmark_query' or 'incident_collection' not defined. Skipping benchmark query logging.")


# -------------------------------
# 4. Example: End-to-End Pipeline Logging
# -------------------------------
# Assuming troubleshooting_pipeline is available
if 'troubleshooting_pipeline' in globals():
    test_query = "Experiencing latency spikes on router X during peak hours"
    # Ensure troubleshooting_pipeline returns a dictionary
    result = troubleshooting_pipeline(test_query, threshold=0.75)

    with mlflow.start_run(run_name="pipeline_run"):
        mlflow.log_param("query", test_query)

        # Log confidence only if it's a numeric value (not None)
        if isinstance(result.get("confidence"), (int, float)):
            mlflow.log_metric("confidence", result["confidence"])
        else:
             print(f"Info: Confidence is None or not numeric ({result.get('confidence')}). Skipping logging confidence metric.")

        # Log processing time if available
        if result.get("processing_time_ms") is not None:
             mlflow.log_metric("processing_time_ms", result["processing_time_ms"])

        mlflow.log_param("agent_source", result.get("agent_source", "unknown"))
        mlflow.log_dict(result, "pipeline_result.json")
else:
    print("Warning: 'troubleshooting_pipeline' not defined. Skipping pipeline run logging.")

# -------------------------------
# 5. Launch MLflow UI (Optional)
# -------------------------------
# This part is moved to main.py to run in a separate process